### ISSUE TITLE
End-user docs available?

### ISSUE THREAD

**Issue by davidjb** [boulder-food-rescue/food-rescue-robot#10]
I'm helping some admins and volunteers get started using the Robot (coming in from the cold so to speak as an IT dev) and wonder if there's any docs or help resources for end users on how to use the system.

Thanks!

**Comment by somerandomsequence** [comment]
Hi David!

To clarify, you're setting up your own instance of the software? If so, that's great! Just so you know, many folks choose to use our instance running at http://robot.boulderfoodrescue.org and by way of 'interactive' documentation we usually temporarily 'assign' new users to Boulder so they can see what an up and running food rescue organization looks like in the robot. If you're keen on that, contact helen@boulderfoodrescue.org or hana@boulderfoodrescue.org. 

For end user docs, we really only have them for the admins (volunteer coordinator, etc.), and they're here: https://docs.google.com/document/d/1Ozhx5MJvmRHehj1D6R7VGWppQ8PysPU6q1ra0rbY7ww/edit?usp=sharing

**Comment by davidjb** [comment]
Fantastic, that's very helpful from the admin perspective. I'll keep in touch about being added as to the existing Boulder group. Cheers!
