### ISSUE TITLE
Add `dotenv` or similar gem

### ISSUE THREAD

**Issue by ericfreese** [boulder-food-rescue/food-rescue-robot#101]
To manage environment variables such as the google maps API key at https://github.com/boulder-food-rescue/food-rescue-robot/blob/54848ced21685a063a743cd560145c77cfed9d60/app/controllers/schedule_chains_controller.rb#L36

**Comment by Laszlo-JFLMTCO** [comment]
@ericfreese I have used [Figaro](https://github.com/laserlemon/figaro) a few times. Any objections against it?

**Comment by ericfreese** [comment]
Thanks @moveson !!
