### ISSUE TITLE
Remove Webapp::Application.config.DayOfWeek 

### ISSUE THREAD

**Issue by cllns** [boulder-food-rescue/food-rescue-robot#16]
In [`config/initializers/constant.rb`](https://github.com/boulder-food-rescue/food-rescue-robot/blob/6fe550eb168aaf9a098580ad9c71c55f537864fc/config/initializers/constant.rb#L1), there's a `Webapp::Application.config.DayOfWeek` setting that's not necessary, since we can use Ruby helpers. That array is only used in [one form](https://github.com/boulder-food-rescue/food-rescue-robot/blob/1deb9cc39fde9e933f7d561530e01d998756bff4/app/views/schedule_chains/_form.html.erb#L14).

I recommend using Ruby's `Date::DAYNAMES`, rather than Rails's `Date::DAYS_INTO_WEEK` since that indexes Monday as 0.

```
Date::DAYNAMES.each_with_index.to_a
# => [["Sunday", 0], ["Monday", 1], ["Tuesday", 2], ["Wednesday", 3], ["Thursday", 4], ["Friday", 5], ["Saturday", 6]]
```

And you can use the `:prompt => "Unknown/varies"` option on the `select` helper to get that option. 

This would be a **great** contribution for a beginner. :)

**Comment by rylanb** [comment]
👍

**Comment by rylanb** [comment]
Fosome fixed it!
