### ISSUE TITLE
'Add to Google Calendar' enhancement request - include region name automatically in event title

### ISSUE THREAD

**Issue by phyninja** [boulder-food-rescue/food-rescue-robot#175]
## Expected Behavior

When the 'Add to Google Calendar' button is pressed, one may expect the resulting calendar event to have the full name of the local food rescue org in the event title. For example 'Boulder Food Rescue'. 

## Actual Behavior

The region is not automatically populated.

### Example URL: 
https://calendar.google.com/calendar/u/0/r/eventedit?text=++++++++++++Food+Rescue:+Sprouts+Market:++Baseline+-%3E+BHP+@+Madison++++++++++++&dates=20200929T150000Z/20200929T170000Z&details&location=2950+Baseline+Rd.+Boulder,+CO+80303&trp=true&sprop=http://boulderfoodrescue.org&sprop=name:Boulder+Food+Rescue&sf=true

### Example Screenshot
![Screen Shot 2020-09-24 at 10 21 31 AM](https://user-images.githubusercontent.com/10854442/94102755-7ca13580-fe50-11ea-96bc-498fe0309275.png)

## Steps to Recreate

1. Navigate to a 'schedule chain' page, eg: https://robot.boulderfoodrescue.org/schedule_chains/774
2. Click on the 'Add to Google Calendar' button.
3. Sign in with Google Account if prompted.

**Comment by rylanb** [comment]
Updated to add this and remove the extra space in front of the title
