### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by kirantpatil** [boulder-food-rescue/food-rescue-robot#29]
Hi,

The current version still on rails 3.2 which is way older.

Please migrate to Rails 5, where it allows to take new features like Turbolinks for mobile app development.

Kiran.

**Comment by rylanb** [comment]
Thank you for your comment Kiran. We are aware of the age of Rails 3.2 and needs to upgrade. If you'd like to contribute to the repository, please do.
