### ISSUE TITLE
asset precompile failures

### ISSUE THREAD

**Issue by mnoky** [boulder-food-rescue/food-rescue-robot#33]
Hi, thanks for making such a wonderful resource available! After some trial and error, I finally got the Robot running for our organization. Still, there are a number of oddities I encountered. The main issue: once I got to the "asset precompile" stage I got a ton of "can't dump anonymous class" errors:

```
bundle exec rake assets:precompile
...
Warning. Error encountered while saving cache /home/user/tmp/food-rescue-robot/cache/sass/0ff4030c6c0d0ceff44d126bd6d5c928f9de1435/home.css.scssc: can't dump anonymous class #<Class:0x0000000545e8e0>
...
rake aborted!
```

After searching around, this seems to be a problem with sass/sprockets: https://github.com/sass/sass/issues/1162. Problem is, I can't seem to get this to work by downgrading sass to an older version such as 3.2.15.

Am I missing something here? How are you able to get the asset precompile to work? I ended up configuring "config.assets.compress = false" for now to get the site working. Thanks for your help!

**Comment by rylanb** [comment]
Hey @mnoky... where are you running this? 

You review this -> https://github.com/rails/sass-rails/issues/242 and didn't find a solution?

**Comment by mnoky** [comment]
Aha, it did work with a couple of tweaks, the recommended sass version was inconsistent in the solution. I added the following to the Gemfile:
```
gem 'sass', '~> 3.2.10'
```
Also, I needed to allocate more memory for my Digital Ocean droplet. Apparently bundler needed more memory to perform the asset precompile, though it took a while to figure out since the error message was vague.

Thank you!

**Comment by rylanb** [comment]
Ah yup! DO can fall over quickly with a RoR process on the $5/mth one. Bit unfortunate. Thanks for the Gemfile update! I'll try to incorporate or you can add a PR if you get time.
