### ISSUE TITLE
Fix assignments link on /volunteers/super_admin

### ISSUE THREAD

**Issue by rylanb** [boulder-food-rescue/food-rescue-robot#51]
## Expected Behavior
/volunteers/super_admin has a link to 'assignments_path' that goes nowhere, was or is not implemented. Need to know why and fix.

## Actual Behavior
Links where? 

## Steps to Recreate
Go to /volunteers/super_admin and see that 'assignments' text link does not work

---

From Hana:

> I wasn't sure but just tried to find that link and did. If I go to "Super Admin," and then I go to "Controls" that is the link it generates and it says the Sorry, something went wrong. That page used to give me the ability to make other people super admins and access data across everyone on the network. The page looked similar to the one that you access when you go to "region admin," and then "controls."

**Comment by Fosome** [comment]
I've been able to reproduce.

Fix:
I'm suggesting we remove that link: https://github.com/boulder-food-rescue/food-rescue-robot/blob/master/app/views/volunteers/super_admin.html.erb#L36

I can't find the link that view would reference, it should be at `app/views/assignments/index.html.erb`.  They must not be following that link.

**Comment by rylanb** [comment]
https://github.com/boulder-food-rescue/food-rescue-robot/commit/bc71312a015086a3785112034a9f4794d9f648bf

**Comment by rylanb** [comment]
Region Admin is PROBABLY the link its supposed to go to now, waiting to hear from Hana.

**Comment by Fosome** [comment]
ping

**Comment by rylanb** [comment]
@Fosome Didn't this get fixed? Feels like it did. 

https://github.com/boulder-food-rescue/food-rescue-robot/blob/master/app/views/volunteers/super_admin.html.erb

Seems good now. 👍
