### ISSUE TITLE
Translation missing on new sign up

### ISSUE THREAD

**Issue by Traci7822** [boulder-food-rescue/food-rescue-robot#79]
## Expected Behavior
Expect sign up to allow new user to create account and log in

## Actual Behavior
After 'Sign up' link is followed and form is submitted the following error appears in the 'Sign in' box:
`translation missing: en.devise.registrations.volunteer.signed_up_but_not_assigned`
When attempting to sign in, the following error is thrown:
`Your account has not been assigned to a region yet. A region administrator must do this before you can sign in.`

## Steps to Recreate
Create new account through sign up from root page

## Environment
OSX - Sierra, Ruby 2.1.5

**Comment by ZebGirouard** [comment]
This happened to me too!

`translation missing: en.devise.registrations.volunteer.signed_up_but_not_assigned`

**Comment by moveson** [comment]
I just submitted PR#87 to address this issue.

**Comment by moveson** [comment]
I believe this issue can be closed.

**Comment by rylanb** [comment]
Pr here: https://github.com/boulder-food-rescue/food-rescue-robot/pull/87

Closed / merged.
