### ISSUE TITLE
Problems with LogPart#scale_weight

### ISSUE THREAD

**Issue by moveson** [boulder-food-rescue/food-rescue-robot#86]
## Expected Behavior
  The comment prior to this method states, "weight in db is always lbs, so convert to what the user expects to see (in the units of the scale)". Based on this comment, I would expect this method would convert a weight in pounds to a weight in other units.

## Actual Behavior
The method reads as follows:
```
  def scale_weight
    display_unit = self.log.scale_type.weight_unit
    if display_unit == 'kg'
      self.weight * 2.2
    elsif display_unit == 'st'
      self.weight * 14
    else
      self.weight
    end
  end
```
This method in fact converts weights in other units (kilograms and stones) to weights in pounds.

## Steps to Recreate
The method appears to be faulty on its face. 

## Suggested Action
It seems one of three things should happen:

1. The method should be deleted. This may be the most appropriate action as it does not appear to be used anywhere in the code.

2. The method should be rewritten to convert pounds to other units of measurement. This would simply require dividing instead of multiplying by the conversion factors.

3. The method should remain functionally unchanged, and the comment should be updated to reflect what the method actually does. This would make sense only if weights in the database are actually stored in other units and we need a method that converts to pounds.

**Comment by ericfreese** [comment]
> The method should be deleted.

Sounds good to me. A git pickaxe for `scale_weight` shows only one commit: 9f8c8e6, the commit that [added it](https://github.com/boulder-food-rescue/food-rescue-robot/commit/9f8c8e6495a3b29f6face03cb2b9a1fb3b799b19#diff-2d5fd730874de4e8b16a5f578a79316bR7). Appears to me it is not used, and has never _been_ used.

**Comment by rylanb** [comment]
Merging in
